// onboarding action
export const SET_ONBOARDING = 'SET_ONBOARDING';
export const SET_ONBOARDING_FAILURE = 'SET_ONBOARDING_FAILURE';
export const SET_ONBOARDING_SUCCESS = 'SET_ONBOARDING_SUCCESS';

// cart action types
export const cartAction = {
  ADD_CART: 'ADD_CART',
  ADD_DETAILS_CART: 'ADD_DETAILS_CART',
  UPDATE_EXISTING_ITEM_QUANTITY:'UPDATE_EXISTING_ITEM_QUANTITY',
  ADD_ITEM_ID: 'ADD_ITEM_ID',
  ADD_ITEM_DETAILS: 'ADD_ITEM_DETAILS',
  CART_FAILURE_ADD: 'CART_FAILURE_ADD',
};

// login action types
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const BOARDING_DONE = 'BOARDING_DONE';
export const LOGOUT = 'LOGOUT';

// signup action types

export const REGISTER_USER= 'REGISTER_USER';
export const REGISTER_USER_SUCCESS= 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE= 'REGISTER_USER_FAILURE';


// Address action types
export const addressActions = {
  SELECT_ADDRESS: 'SELECT_ADDRESS',
  SELECT_ADDRESS_SUCCESS: 'SELECT_ADDRESS_SUCCESS',
  SELECT_ADDRESS_FAILURE: 'SELECT_ADDRESS_FAILURE',
};
